In [1]:
import pandas as pd

In [2]:
dados_vendas = {
    'Produto': ['Camisa', 'Calça', 'Saia', 'Camisa', 'Calça', 'Saia', 'Camiseta', 'Calça', 'Saia'],
    'Preço': [50, 100, 80, 55, 110, 85, 45, 95, 90],
    'Quantidade': [10, 15, 20, 5, 10, 15, 30, 20, 10],
    'Mês': ['Jan', 'Jan', 'Jan', 'Fev', 'Fev', 'Fev', 'Mar', 'Mar', 'Mar']
}

In [3]:
df_vendas = pd.DataFrame(dados_vendas)
df_vendas

    Produto  Preço  Quantidade  Mês
0    Camisa     50          10  Jan
1     Calça    100          15  Jan
2      Saia     80          20  Jan
3    Camisa     55           5  Fev
4     Calça    110          10  Fev
5      Saia     85          15  Fev
6  Camiseta     45          30  Mar
7     Calça     95          20  Mar
8      Saia     90          10  Mar

In [5]:
# Calculando a Receita Total
df_vendas['Receita'] = df_vendas['Preço'] * df_vendas['Quantidade']
df_vendas

    Produto  Preço  Quantidade  Mês  Receita
0    Camisa     50          10  Jan      500
1     Calça    100          15  Jan     1500
2      Saia     80          20  Jan     1600
3    Camisa     55           5  Fev      275
4     Calça    110          10  Fev     1100
5      Saia     85          15  Fev     1275
6  Camiseta     45          30  Mar     1350
7     Calça     95          20  Mar     1900
8      Saia     90          10  Mar      900

In [6]:
# Sumarizando a receita total por produto - agrupando com base na receita dos produtos
resumo_vendas = df_vendas.groupby('Produto')['Receita'].sum().reset_index()
resumo_vendas

    Produto  Receita
0     Calça     4500
1    Camisa      775
2  Camiseta     1350
3      Saia     3775

In [7]:
# Filtrando produtos com receita acima de R$ 1000
produtos_altas_vendas = resumo_vendas[resumo_vendas['Receita'] > 1000]
produtos_altas_vendas

    Produto  Receita
0     Calça     4500
2  Camiseta     1350
3      Saia     3775

In [13]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'