- Um DataFrame no Pandas é uma estrutura de dados bidimensional, semelhante a uma tabela de banco de dados (como o SQL) ou a uma planilha do Excel. Ele organiza os dados em linhas e colunas

In [1]:
import pandas as pd

In [2]:
dados = {
    'Nome': ['Alice', 'Bob', 'Charlie'],
    'Idade': [24, 30, 22],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
}

In [ ]:
df = pd.DataFrame(dados)  #df é de Data Frame

In [4]:
df

      Nome  Idade          Cidade
0    Alice     24       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     22  Belo Horizonte

In [6]:
df.head(1)

    Nome  Idade     Cidade
0  Alice     24  São Paulo

In [7]:
df.tail(1)

      Nome  Idade          Cidade
2  Charlie     22  Belo Horizonte

In [8]:
dados_notas = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Matemática':[85, 90, 78, 88, 92],
    'Física': [80, 75, 88, 85, 95],
    'Química': [78, 82, 85, 80, 88]
}

In [9]:
df_notas = pd.DataFrame(dados_notas)

In [10]:
df_notas

      Nome  Matemática  Física  Química
0    Alice          85      80       78
1      Bob          90      75       82
2  Charlie          78      88       85
3    David          88      85       80
4      Eva          92      95       88

In [11]:
#Calculando a média das notas por aluno
df_notas['Média'] = df_notas[['Matemática', 'Física', 'Química']].mean(axis=1)
df_notas

      Nome  Matemática  Física  Química      Média
0    Alice          85      80       78  81.000000
1      Bob          90      75       82  82.333333
2  Charlie          78      88       85  83.666667
3    David          88      85       80  84.333333
4      Eva          92      95       88  91.666667

In [12]:
#Identificar alunos aprovados com nota boa (média >= 82.5)
alunos_aprovados = df_notas[df_notas['Média'] >= 82.5]
alunos_aprovados

      Nome  Matemática  Física  Química      Média
2  Charlie          78      88       85  83.666667
3    David          88      85       80  84.333333
4      Eva          92      95       88  91.666667

In [ ]:
#Exibir a media e os alunos
df_notas[['Nome','Média']]

      Nome      Média
0    Alice  81.000000
1      Bob  82.333333
2  Charlie  83.666667
3    David  84.333333
4      Eva  91.666667

In [15]:
#Exibir a media e os alunos aprovados
alunos_aprovados[['Nome','Média']]

      Nome      Média
2  Charlie  83.666667
3    David  84.333333
4      Eva  91.666667