In [1]:
import pandas as pd

In [2]:
df_produtos = pd.read_csv("dados/produtos.csv")
df_produtos

       Produto   Categoria  Preço  Quantidade  Data_Venda
0       Camisa      Roupas   50.0          10  2023-01-01
1        Calça      Roupas  100.0          15  2023-01-02
2         Saia      Roupas   80.0          20  2023-01-03
3     Camiseta      Roupas   45.0          30  2023-01-04
4      Jaqueta      Roupas  120.0           5  2023-01-05
5      Vestido      Roupas   90.0          12  2023-01-06
6      Bermuda      Roupas   60.0          18  2023-01-07
7       Sapato    Calçados  150.0           7  2023-01-08
8     Sandália    Calçados   70.0          25  2023-01-09
9        Tênis    Calçados  200.0           8  2023-01-10
10       Botas    Calçados  180.0           6  2023-01-11
11     Mochila  Acessórios   70.0          15  2023-01-12
12       Cinto  Acessórios   40.0          22  2023-01-13
13      Óculos  Acessórios  120.0          10  2023-01-14
14     Relógio  Acessórios  250.0           4  2023-01-15
15      Brinco  Acessórios   35.0          30  2023-01-16
16       Blusa      Roupas   55.0          14  2023-01-17
17      Shorts      Roupas   65.0          19  2023-01-18
18      Suéter      Roupas   95.0           9  2023-01-19
19  Saia longa      Roupas   75.0          11  2023-01-20

In [3]:
df_produtos.dtypes

Produto           str
Categoria         str
Preço         float64
Quantidade      int64
Data_Venda        str
dtype: object

In [5]:
#Deixa a coluna para numerico
df_produtos['Quantidade'] = pd.to_numeric(df_produtos['Quantidade'])
df_produtos['Preço'] = pd.to_numeric(df_produtos['Preço'])

In [6]:
#1-Desempenho de Vendas por Categoria
vendas_categoria = df_produtos.groupby('Categoria')['Quantidade'].sum()
vendas_categoria

Categoria
Acessórios     81
Calçados       46
Roupas        163
Name: Quantidade, dtype: int64

In [9]:
#2-Produto mais vendido
produto_mais_vendido = df_produtos.groupby('Produto')['Quantidade'].sum().idxmax()
produto_mais_vendido

'Brinco'

In [10]:
#3-Total de Unidades Vendidas por Produto
produto_mais_vendido = df_produtos.groupby('Produto')['Quantidade'].sum()
produto_mais_vendido

Produto
Bermuda       18
Blusa         14
Botas          6
Brinco        30
Calça         15
Camisa        10
Camiseta      30
Cinto         22
Jaqueta        5
Mochila       15
Relógio        4
Saia          20
Saia longa    11
Sandália      25
Sapato         7
Shorts        19
Suéter         9
Tênis          8
Vestido       12
Óculos        10
Name: Quantidade, dtype: int64

In [12]:
#4-Preço Médio por Produto
media_preco_produto = df_produtos.groupby('Produto')['Preço'].mean()
media_preco_produto

Produto
Bermuda        60.0
Blusa          55.0
Botas         180.0
Brinco         35.0
Calça         100.0
Camisa         50.0
Camiseta       45.0
Cinto          40.0
Jaqueta       120.0
Mochila        70.0
Relógio       250.0
Saia           80.0
Saia longa     75.0
Sandália       70.0
Sapato        150.0
Shorts         65.0
Suéter         95.0
Tênis         200.0
Vestido        90.0
Óculos        120.0
Name: Preço, dtype: float64

In [14]:
#5-Correlação entre Unidades Vendidas e Preço Unitário
correlacao = df_produtos['Quantidade'].corr(df_produtos['Preço'])
correlacao

np.float64(-0.7228821786680254)

In [16]:
""" Esse código está fazendo uma transformação bem comum em Pandas: 
pegando um DataFrame/Series que provavelmente tem a categoria como 
índice e transformando esse índice em uma coluna normal

- reset_index() tira o índice da posição de índice e transforma em uma coluna.

"""

vendas_categoria_df = vendas_categoria.reset_index()
vendas_categoria_df.columns = ['Categoria', 'Unidades Vendidas']
vendas_categoria_df

    Categoria  Unidades Vendidas
0  Acessórios                 81
1    Calçados                 46
2      Roupas                163

In [17]:
# Exportar o arquivo
vendas_categoria_df.to_csv("dados/vendas_categoria.csv", index=False)